### ISSUE TITLE
/dev/ttyUSB0 

### ISSUE THREAD

**Issue by mvogt1** [adamoutler/HassOSDeskPiPro#1]
The script run.sh uses /dev/ttyUSB0 as serial device. 
This does not work with another serial device (eg: zzh zigbee stick).

I have tested:

echo -ne "pwm_100" >/dev/ttyUSB1

with this, the fan works.

**Comment by adamoutler** [comment]
I'm working on it.  I got side tracked and found I could increase the security rating to 6 by adding a property.  The code is done and I will push it tomorrow after some cleanup.

**Comment by mvogt1** [comment]
Many thanks, I just downloaded it, it works now.
