### ISSUE TITLE
Strange behaviour together with zigbee2mqtt

### ISSUE THREAD

**Issue by mvogt1** [adamoutler/HassOSDeskPiPro#2]
Today I tested again the addon, I had some problems with it in the past and disabled it for a longer time.
This time I had the intention to make a bug report, if I still cannot make it work.

## In Short

I have trouble running zigbee2mqtt together with the DeskPi Pro version 0.6 addon.

## 0 The issue

The zigbee2mqtt web Gui does not start or if it starts it does not work correctly, if I enable DeskPro Pro with "Start on boot".

If it does not start I get: Bad gateway
If it starts but does not work correctly:  I cannot send on/off commands to the lamps.

How to reproduce:

## 1. Start

- No DeskPi Pro installed
- zigbee2mqtt web Gui works fine

Now I install DeskPi,  I get in the system log:

21-04-17 15:51:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
21-04-17 15:51:42 WARNING (MainThread) [supervisor.addons.validate] __Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of DeskPi Pro Active Cooling__
21-04-17 15:51:42 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of DeskPi Pro Active Cooling

Set "Start on boot" in DeskPri Pro to :false
Enable:

dtoverlay=dwc2,dr_mode=host

in config.txt

## 2. Reboot 1

After a reboot (DeskPi Pro does not autostart):

- zigbee2mqtt and the zigbee2mqtt web gui works.

Now I change the serial device in DeksPi to /dev/ttyUSB1
and starting DeskPi Pro 

The system log reports:

21-04-17 15:59:18 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker

The DeskPi Pro  log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
__nc: bind: Address in use__
Current Temperature 105 °F
Quiet Level 2 - Fan 20% (Low)

The zigbee2mqtt WebGui still works.

Now I set "Start on boot" in DeskPi Pro to : true

Now I reboot.

## 3. Reboot 2

web gui hangs.
__Note:__ Both use port 8099, but in DeskPi Pro this is not configurable.
Changing it in zigbee2mqtt gives a __Bad Gateway__ error.

Here are the system logs, after Reboot 2:

21-04-17 16:29:08 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.2-1
21-04-17 16:29:48 ERROR (MainThread) [supervisor.api.ingress] __Ingress error: Cannot connect to host 172.30.33.2:8099 ssl:default [Connect call failed ('172.30.33.2', 8099)]__
21-04-17 16:38:04 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.2:8099 ssl:default [Connect call failed ('172.30.33.2', 8099)]
21-04-17 16:38:07 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.2:8099 ssl:default [Connect call failed ('172.30.33.2', 8099)]
21-04-17 16:38:08 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD usb hardware /dev/bus/usb/001/004
21-04-17 16:38:08 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD serial hardware /dev/ttyUSB0 - /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_4F_3F_2
21-04-17 16:38:10 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.2:8099 ssl:default [Connect call failed ('172.30.33.2', 8099)]
21-04-17 16:38:52 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_45df7312_zigbee2mqtt application
21-04-17 16:38:56 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application
21-04-17 16:39:00 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.2-1

This time I needed to re-flash the zigbee stick in order to make 
it work again. So maybe there is some trouble with the ttyUSB0 / 1 too.

I needed to change the usb ports from back/front and the to back.
reboot. Very strange.

**Comment by adamoutler** [comment]
OK, so the Desk Pi pro, once the serial port is enabled, will generally be ttyUSB0 unless you're able to override that somehow.  It's possible, but unlikely.   DeskPi Pro's stock firmware is hard coded to ttyUSB0.  You may need to set some udev rules to fix ttyUSB0 and ttyUSB1 as a specific device.    

Don't worry about the 8099 thing.  Each addon can use port 8099.  I'm not sure why you saw that error, but it's irrelevant.   

You should probably plug the stick into the back ports as the front ones are reinitialized during bootup and that can cause problems with devices.

**Comment by mvogt1** [comment]
Maybe this strange behaviour is power related. In dmesg I get:

>cp210x ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32

Here USB0 is the zigbee stick and DeskPi Pro is not running, but the overlay
for USB front is enabled in config.txt.

Then switching the zigbee2mqtt to front works, and if I switch it back it does not work,
but if I do it a few more times, it even works on both side. Most likely it will fail
on the front too, after some time. Its a raspi4 with SSD.

Thus maybe enabling:

dtoverlay=dwc2,dr_mode=host

is the problem. I'm using the deskpripro powersupply.
For the usb urb error error there is a entry in the zigbee2mqtt issue tracker:

https://github.com/Koenkk/Z-Stack-firmware/issues/205

**Comment by adamoutler** [comment]
The issue you linked specifies problems ranging from hardware failure to power supply issues.  One person is mentioning it occurs on a totally different platform.  You should try a new power supply and RPi.

**Comment by mcmatti** [comment]
After disabling the plugin and removing the raspi from the deskpi board everything was stable. Of course, the Zigebee stick must be on a extension cable, but that was true the whole time.

Today the new board arrived, mine was a pre-order verson.
According to the deskpi Webpage they solved some stability issues:

The new updated PCB Boards fixes following problems:
1. The problem with USB booting --- identifying SSDs
2. WiFi interference issues
3. HDMI display problem
4. Compatibility issues of Wireless key & mouse

Im testing..

**Comment by mvogt1** [comment]
The new board seems to fix my issues.
==> closed
