### ISSUE TITLE
Question about your Add-On

### ISSUE THREAD

**Issue by Electronlibre2012** [adamoutler/HassOSDeskPiPro#3]
Hello @adamoutler 

first, thanks for your add-on, work great!

I have a question : what is supposed to be in the "Web UI" please?

because i have only a text : "DeskPi Pro Active Cooling! " and nothing more...i wished some graphics temp and trigger with temp...lol

Thanks for your reply,

have a nice day ;)

**Comment by adamoutler** [comment]
Yeah, I need to remove that.
