### ISSUE TITLE
could not find /dev/ttyUSB0

### ISSUE THREAD

**Issue by jaswalters** [adamoutler/HassOSDeskPiPro#4]
Please note. I am running an RPI with an SSD drive attached internally.
DeskPI V. 2.0

I ran the commands to add the required info to config.txt and I can open the file and see it is present.

Log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
could not find /dev/ttyUSB0. This addon cannot continue without a serial device. Here is a list of possible SerialDevice:
ls: /dev/ttyUSB*: No such file or directory
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Any more info I can provide?

**Comment by rickbeumers** [comment]
Same issue here, I was checking the folders for ttyUSB0 but it doesn't exists for me.

The folder `/dev/tty*` only contains numbers from `tty0` till `tty63` and `ttyAMA0` and `ttypintk`.

Im am using an M.2 SATA ssd, not sure if that complicates things here?

**Comment by jaswalters** [comment]
Same here, using an M.2 Sata and I see the same result for tty*. I've been trying to dig into this and see what I can discover.

Seems like we're onto something since we're both using the same drive type and same results.

**Comment by adamoutler** [comment]
You have to enable pi serial. There is a guide on HA and an add-on I wrote to do this.

**Comment by rickbeumers** [comment]
@adamoutler thank you for your response, that indeed did the trick.

For people having this issue: https://community.home-assistant.io/t/add-on-hassos-serial-configurator/264169
